"""Usersignup table add the properties in passive delete.

Revision ID: 035dc82bfba9
Revises: c3c0de936ac3
Create Date: 2025-07-11 05:23:21.096682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035dc82bfba9'
down_revision: Union[str, Sequence[str], None] = 'c3c0de936ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
